[package]
name = "dht-sensor"
version = "0.1.0"
description = "Driver for the DHT11/DHT22 sensor based on embedded-hal"
authors = ["Michael Beaumont <mjboamail@gmail.com>"]
keywords = ["embedded", "sensor", "humidity", "temperature", "embedded-hal-driver"]
categories = ["embedded", "no-std", "hardware-support"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/michaelbeaumont/dht-sensor"

[dependencies]
embedded-hal = "0.2.3"

[dev-dependencies]
stm32f0xx-hal = {version = "*", features = ["stm32f042"]}
cortex-m = "0.6.1"
cortex-m-rt = "0.6.11"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
stm32f0 = {version = "0.9.0", features = ["stm32f0x2"]}

[profile.release]
codegen-units = 1
debug = true
lto = true
